# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-11
# Copyright  : Copyright (C) 2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : owserver/Dockerfile-rpi
# Version    : 0.1.0
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM resin/rpi-raspbian:latest

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apt-get update && \
    apt-get install -y vim \
                       owfs-fuse && \
    rm -rf /var/lib/apt/lists* && \
    mkdir -p /mnt/1wire

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV OWSERVER_IP_ADDR 127.0.0.1
ENV OWSERVER_PORT_NO 4304

ENV DOCKER_BASE_IMAGE_NAME na
ENV DOCKER_BASE_IMAGE_TAG na

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

#-------------------------------------------------------------------
# Expose a Volume the owfs file tree
#-------------------------------------------------------------------

VOLUME /mnt/1wire

ENTRYPOINT /usr/bin/owfs -s ${OWSERVER_IP_ADDR}:${OWSERVER_PORT_NO} -m /mnt/1wire/
